### ISSUE TITLE
Bootcamps: upgrade Pillow to 9.0.0 or higher

### ISSUE THREAD

**Issue by umarmughal824** [mitodl/bootcamp-ecommerce#1323]
Bootcamps: upgrade Pillow to 9.0.0 or higher

**Comment by umarmughal824** [comment]
It also requires to update django and wagtail

**Comment by umarmughal824** [comment]
facing these issues while updation

```
 ~/a/MIT/bootcamp-ecommerce  umar/update-pillow *10 !1 ?3  docker-compose exec web bas
h
mitodl@564e32735faa:/src$ pip-compile requirements.in
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/piptools/scripts/compile.py", line 313, in cli
    repository = PyPIRepository(pip_args, cache_dir=cache_dir)
  File "/usr/local/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 93, in __init__
    self._setup_logging()
  File "/usr/local/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 451, in _setup_logging
    assert isinstance(handler, logging.StreamHandler)
AssertionError```
