### ISSUE TITLE
Warnings & Exception in local logs

### ISSUE THREAD

**Issue by asadali145** [mitodl/bootcamp-ecommerce#1583]
### Description/Context
I have noticed a couple of warnings in the logs while reviewing https://github.com/mitodl/bootcamp-ecommerce/pull/1538.

1. Visit Any CMS Page. You will see an exception in the logs:
```
Traceback (most recent call last):
web-1     |   File "/opt/venv/lib/python3.10/site-packages/django/template/base.py", line 886, in _resolve_lookup
web-1     |     if isinstance(current, BaseContext) and getattr(
web-1     | AttributeError: type object 'Context' has no attribute 'header_controls'
web-1     | 
web-1     | During handling of the above exception, another exception occurred:
web-1     | 
web-1     | Traceback (most recent call last):
web-1     |   File "/opt/venv/lib/python3.10/site-packages/django/template/base.py", line 896, in _resolve_lookup
web-1     |     current = current[int(bit)]
web-1     | ValueError: invalid literal for int() with base 10: 'header_controls'
web-1     | 
web-1     | During handling of the above exception, another exception occurred:
web-1     | 
web-1     | Traceback (most recent call last):
web-1     |   File "/opt/venv/lib/python3.10/site-packages/django/template/base.py", line 903, in _resolve_lookup
web-1     |     raise VariableDoesNotExist(

```
2. A warning related to restframework:
```
[2024-07-25 11:19:18] WARNING 9 [rest_framework.fields] fields.py:994 - [b3526855c953] - min_value in DecimalField should be Decimal type.
```
3. A warning related to UWSGI:
```
/opt/venv/lib/python3.10/site-packages/sentry_sdk/_compat.py:85: Warning: IMPORTANT: We detected the use of uWSGI in preforking mode without thread support. This might lead to crashing workers. Please run uWSGI with both "--enable-threads" and "--py-call-uwsgi-fork-hooks" for full support.
```

### Plan/Design

- R&D and fix issues.
- We have a PR in xPro to fix the uwsgi warning: https://github.com/mitodl/mitxpro/pull/3005

**Comment by arslanashraf7** [comment]
@Anas12091101 Can you take a look at this?
