### ISSUE TITLE
Exception while resolving variable 'name'

### ISSUE THREAD

**Issue by shaidar** [mitodl/bootcamp-ecommerce#837]
Came across this continuously repeating error in the logs on production.
```
2020-06-30T15:25:35.250170+00:00 app[web.1]: [2020-06-30 15:25:35] DEBUG 539 [django.template] base.py:872 - [9fa57539-c1cb-40f4-ac7d-91a55cd06170] - Exception while resolving variable 'name' in template 'bootcamp/index.html'.
2020-06-30T15:25:35.250172+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250173+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
2020-06-30T15:25:35.250174+00:00 app[web.1]: current = current[bit]
2020-06-30T15:25:35.250174+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.250174+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.250175+00:00 app[web.1]: TypeError: 'AnonymousUser' object is not subscriptable
2020-06-30T15:25:35.250176+00:00 app[web.1]:
2020-06-30T15:25:35.250176+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.250177+00:00 app[web.1]:
2020-06-30T15:25:35.250177+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250178+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
2020-06-30T15:25:35.250178+00:00 app[web.1]: current = getattr(current, bit)
2020-06-30T15:25:35.250179+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.250179+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.250179+00:00 app[web.1]: AttributeError: 'AnonymousUser' object has no attribute 'name'
2020-06-30T15:25:35.250180+00:00 app[web.1]:
2020-06-30T15:25:35.250180+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.250180+00:00 app[web.1]:
2020-06-30T15:25:35.250181+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250181+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
2020-06-30T15:25:35.250181+00:00 app[web.1]: current = current[int(bit)]
2020-06-30T15:25:35.250182+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'name'
2020-06-30T15:25:35.250182+00:00 app[web.1]:
2020-06-30T15:25:35.250183+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.250183+00:00 app[web.1]:
2020-06-30T15:25:35.250183+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250184+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
2020-06-30T15:25:35.250184+00:00 app[web.1]: (bit, current))  # missing attribute
2020-06-30T15:25:35.250191+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f5a18dc85c0>>
2020-06-30T15:25:35.250311+00:00 app[web.1]: [2020-06-30 15:25:35] DEBUG 539 [django.template] base.py:872 - [9fa57539-c1cb-40f4-ac7d-91a55cd06170] - Exception while resolving variable 'name' in template 'bootcamp/index.html'.
2020-06-30T15:25:35.250312+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250313+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
2020-06-30T15:25:35.250314+00:00 app[web.1]: current = current[bit]
2020-06-30T15:25:35.250314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.250314+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.250315+00:00 app[web.1]: TypeError: 'AnonymousUser' object is not subscriptable
2020-06-30T15:25:35.250315+00:00 app[web.1]:
2020-06-30T15:25:35.250316+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.250316+00:00 app[web.1]:
2020-06-30T15:25:35.250316+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250317+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
2020-06-30T15:25:35.250317+00:00 app[web.1]: current = getattr(current, bit)
2020-06-30T15:25:35.250318+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.250318+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.250318+00:00 app[web.1]: AttributeError: 'AnonymousUser' object has no attribute 'name'
2020-06-30T15:25:35.250319+00:00 app[web.1]:
2020-06-30T15:25:35.250319+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.250319+00:00 app[web.1]:
2020-06-30T15:25:35.250320+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250320+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
2020-06-30T15:25:35.250320+00:00 app[web.1]: current = current[int(bit)]
2020-06-30T15:25:35.250321+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'name'
2020-06-30T15:25:35.250321+00:00 app[web.1]:
2020-06-30T15:25:35.250322+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.250322+00:00 app[web.1]:
2020-06-30T15:25:35.250322+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.250323+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
2020-06-30T15:25:35.250323+00:00 app[web.1]: (bit, current))  # missing attribute
2020-06-30T15:25:35.250328+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f5a18dc85c0>>
2020-06-30T15:25:35.251162+00:00 app[web.1]: [2020-06-30 15:25:35] DEBUG 539 [django.template] base.py:872 - [9fa57539-c1cb-40f4-ac7d-91a55cd06170] - Exception while resolving variable 'email' in template 'bootcamp/index.html'.
2020-06-30T15:25:35.251163+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251163+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
2020-06-30T15:25:35.251164+00:00 app[web.1]: current = current[bit]
2020-06-30T15:25:35.251164+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.251165+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.251165+00:00 app[web.1]: TypeError: 'AnonymousUser' object is not subscriptable
2020-06-30T15:25:35.251165+00:00 app[web.1]:
2020-06-30T15:25:35.251166+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.251166+00:00 app[web.1]:
2020-06-30T15:25:35.251167+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251167+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
2020-06-30T15:25:35.251167+00:00 app[web.1]: current = getattr(current, bit)
2020-06-30T15:25:35.251168+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.251168+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.251168+00:00 app[web.1]: AttributeError: 'AnonymousUser' object has no attribute 'email'
2020-06-30T15:25:35.251169+00:00 app[web.1]:
2020-06-30T15:25:35.251169+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.251171+00:00 app[web.1]:
2020-06-30T15:25:35.251171+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251172+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
2020-06-30T15:25:35.251172+00:00 app[web.1]: current = current[int(bit)]
2020-06-30T15:25:35.251173+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'email'
2020-06-30T15:25:35.251173+00:00 app[web.1]:
2020-06-30T15:25:35.251173+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.251174+00:00 app[web.1]:
2020-06-30T15:25:35.251174+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251174+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
2020-06-30T15:25:35.251175+00:00 app[web.1]: (bit, current))  # missing attribute
2020-06-30T15:25:35.251180+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [email] in <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f5a18dc85c0>>
2020-06-30T15:25:35.251250+00:00 app[web.1]: [2020-06-30 15:25:35] DEBUG 539 [django.template] base.py:872 - [9fa57539-c1cb-40f4-ac7d-91a55cd06170] - Exception while resolving variable 'email' in template 'bootcamp/index.html'.
2020-06-30T15:25:35.251251+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251252+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
2020-06-30T15:25:35.251252+00:00 app[web.1]: current = current[bit]
2020-06-30T15:25:35.251253+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.251253+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.251254+00:00 app[web.1]: TypeError: 'AnonymousUser' object is not subscriptable
2020-06-30T15:25:35.251254+00:00 app[web.1]:
2020-06-30T15:25:35.251255+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.251255+00:00 app[web.1]:
2020-06-30T15:25:35.251255+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251256+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
2020-06-30T15:25:35.251256+00:00 app[web.1]: current = getattr(current, bit)
2020-06-30T15:25:35.251256+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 257, in inner
2020-06-30T15:25:35.251257+00:00 app[web.1]: return func(self._wrapped, *args)
2020-06-30T15:25:35.251257+00:00 app[web.1]: AttributeError: 'AnonymousUser' object has no attribute 'email'
2020-06-30T15:25:35.251258+00:00 app[web.1]:
2020-06-30T15:25:35.251258+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.251259+00:00 app[web.1]:
2020-06-30T15:25:35.251259+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251260+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
2020-06-30T15:25:35.251260+00:00 app[web.1]: current = current[int(bit)]
2020-06-30T15:25:35.251260+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'email'
2020-06-30T15:25:35.251261+00:00 app[web.1]:
2020-06-30T15:25:35.251261+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2020-06-30T15:25:35.251261+00:00 app[web.1]:
2020-06-30T15:25:35.251262+00:00 app[web.1]: Traceback (most recent call last):
2020-06-30T15:25:35.251262+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 850, in _resolve_lookup
2020-06-30T15:25:35.251262+00:00 app[web.1]: (bit, current))  # missing attribute
2020-06-30T15:25:35.251306+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [email] in <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f5a18dc85c0>>
```

**Comment by pdpinch** [comment]
Is there a reason why this doesn't show up in Sentry?

**Comment by rhysyngsun** [comment]
There debug statements are happening because there's code referencing `user.name` in a template somewhere that doesn't assert that the user is logged in. Probably worth checking for other usages of `User` properties that `AnonymousUser` doesn't have as well.
